---
# tasks file for builder

- name: Clone git repo
  git: repo={{ repo }} dest={{ repo_path }} force=yes

- name: LineInFile example
  lineinfile:
    path: "{{ repo_path }}/{{ file_to_change }}"
    regexp: "<h1>(.*)</h1>"
    line: "<h1>Built on {{ ansible_lsb.description }}</h1>"

- name: Ensure previously built artifact is absent
  file: path={{ war_path }} state=absent

- name: Start Maven container and build artifact
  docker_container:
    name: builder
    image: maven:3.6-alpine
    volumes:
      "{{ repo_path }}:/git"
    command: mvn -f /git/pom.xml clean package
    restart: yes
    detach: no

- name: Ensure newly built artifact is present
  file: path={{ war_path }}

- name: Copy Dockerfile to Build-node
  copy: src=builder/files/Dockerfile dest={{ repo_path }}

- name: Add insecure Docker repository
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": ["{{ docker_registry }}"]
      }

- name: Restart Docker
  service: name=docker state=restarted

- name: Login to Docker registry
  docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ docker_login }}"
    password: "{{ docker_password }}"

- name: Build production image and push it to Docker registry
  docker_image:
    name: "{{ app_image }}"
    source: build
    build:
      path: "{{ repo_path }}"
      args:
        artifact: target/{{ app }}.war
    push: yes
  notify: Remove image