---
- name: Provision Build and Run nodes
  hosts: localhost
  user: ubuntu
  gather_facts: false
  tags: provision

  roles:
    - ec2

- name: Build-server configuration
  hosts: build
    vars:
      ansible_ssh_private_key_file: ~/.ssh/ec2.pem
  user: ubuntu
  become: yes
  tags: build

  roles:
    - common
    - builder

- name: Run-server configuration
  hosts: run
    vars:
      ansible_ssh_private_key_file: ~/.ssh/ec2.pem
  user: ubuntu
  become: yes
  tags: run

  roles:
    - common
    - runner