---
- name: Build-server configuration
  hosts: build
  become: yes
  tags: build

  roles:
    - common
    - builder

- name: Run-server configuration
  hosts: run
  become: yes
  tags: run

  roles:
    - common
    - runner