---
# tasks file for runner

- name: Remove old container
  docker_container:
    name: run
    state: absent

- name: Remove old image
  docker_image:
    name: "{{ app_image }}"
    state: absent

- name: Login to Docker registry
  docker_login:
    username: "{{ docker_login }}"
    password: "{{ docker_password }}"
    
- name: Run app container at production server
  docker_container:
    name: run
    image: "{{ app_image }}"
    ports: "8080:8080"
    recreate: yes