---
# tasks file for common

- name: Ensure Docker is installed
  apt: name={{item}} state=present
  with_items:
    - docker.io
    - python3-docker

- name: Ensure Docker service is running
  service: name=docker state=started