---
- name: Provision an EC2 builder node
  amazon.aws.ec2_instance:
    name: Builder
    key_name: devops
    instance_type: t3.micro
    security_group: SSHAccess
    network:
      assign_public_ip: true
    image_id: ami-0440e5026412ff23f # Ubuntu22.04@eu-north-1
    tags:
      Environment: build
  register: result

- name: Provision an EC2 runner node
  amazon.aws.ec2_instance:
    name: Runner
    key_name: devops
    instance_type: t3.micro
    security_group: SSHAccess
    network:
      assign_public_ip: true
    image_id: ami-0440e5026412ff23f # Ubuntu22.04@eu-north-1
    tags:
      Environment: run
  register: result