---
- name: Provision an EC2 builder node
  ec2_instance:
    name: Builder
    state: started
    wait: true
    key_name: devops
    instance_type: t3.micro
    security_group: SSHAccess
    network:
      assign_public_ip: true
    image_id: ami-0440e5026412ff23f # Ubuntu22.04@eu-north-1
    tags:
      Environment: build
  register: builder

- debug:
    msg: "{{builder}}"
- name: Add builder instance public IPs to build group
  add_host: hostname={{ item.public_ip_address }} groups=build
  loop: "{{ builder.instances }}"

- name: Provision an EC2 runner node
  ec2_instance:
    name: Runner
    state: started
    wait: true
    key_name: devops
    instance_type: t3.micro
    security_group: SSHAccess
    network:
      assign_public_ip: true
    image_id: ami-0440e5026412ff23f # Ubuntu22.04@eu-north-1
    tags:
      Environment: run
  register: runner

- name: Add runner instance public IPs to run group
  add_host: hostname={{ item.public_ip_address }} groups=run
  loop: "{{ runner.instances }}"